# Generated by Django 5.0.6 on 2024-06-15 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home_login_signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='supCreateProject',
            fields=[
                ('projId', models.BigAutoField(primary_key=True, serialize=False)),
                ('projName', models.CharField(max_length=50)),
                ('projDetails', models.TextField()),
                ('startDate', models.DateField()),
                ('endDate', models.DateField()),
                ('approveOrNot', models.BooleanField(default=True)),
                ('highestStudents', models.IntegerField()),
                ('supProjId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home_login_signup.userauthentable')),
            ],
        ),
    ]
