# Generated by Django 5.0.6 on 2024-06-15 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='userAuthenTable',
            fields=[
                ('userId', models.BigAutoField(primary_key=True, serialize=False)),
                ('userType', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('gmail', models.CharField(max_length=50)),
                ('userName', models.CharField(max_length=30)),
                ('passWord', models.CharField(max_length=40)),
            ],
        ),
    ]
